apiVersion: apps/v1
kind: Deployment
metadata:
  name: acoustic-search-app
  labels:
    app: acoustic-search-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : acoustic-search-app
  template:
    metadata:
      labels:
        app: acoustic-search-app
    spec:
      containers:
      - name: acoustic-search-app
        image: niksdocker2233/acoustic-search:0.0.1
        command: ["java"]
        args: ["-jar", "-Dspring.profiles.active=dev", "/app.jar"]
        imagePullPolicy: Never
        ports:
          - containerPort: 8077
        env:
          - name: ZIPKIN_URL
            value: "http://zipkin.dist-tracing.svc.cluster.local:9411"
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
                configMapKeyRef:
                  name: acoustic-cm
                  key: eureka_service_address
---

kind: Service
apiVersion: v1
metadata:
  name:  acoustic-search-app-svc
  labels:
    app: acoustic-search-app
spec:
  selector:
    app:  acoustic-search-app
  ports:
  - port:  80
    targetPort:  8077
    name: http
    