apiVersion: v1
kind: ConfigMap
metadata:
  name: acoustic-cm
data:
  eureka_service_address: http://acoustic-0.acoustic:8067/eureka,http://acoustic-1.acoustic:8067/eureka
  eureka_hostname: eureka

---

apiVersion: v1
kind: Service
metadata:
  name: acoustic
  labels:
    app: acoustic
spec:
  clusterIP: None
  ports:
    - port: 8067
      name: acoustic
  selector:
    app : acoustic

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: acoustic
spec:
  serviceName: "acoustic"
  replicas: 2
  selector:
    matchLabels:
      app: acoustic
  template:
    metadata:
      labels:
        app: acoustic
    spec:
      containers:
        - name: acoustic
          image: niksdocker2233/acoustic-registry:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8067
          env:
            - name: eureka.client.registerWithEureka
              value: "true"
            - name: eureka.client.fetchRegistry
              value: "true"
            - name: eureka.instance.hostname
              value: "${HOSTNAME}.acoustic"
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: acoustic-cm
                  key: eureka_service_address
            - name: EUREKA_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: acoustic-cm
                  key: eureka_hostname    
          livenessProbe:
           httpGet:
            path: /
            port: 8067
           initialDelaySeconds: 15
           periodSeconds: 10
           timeoutSeconds: 5
          readinessProbe:
           httpGet:
             path: /
             port: 8067
           initialDelaySeconds: 15
           periodSeconds: 10
           timeoutSeconds: 5
---                  

apiVersion: v1
kind: Service
metadata:
  name: acoustic-np
  labels:
    app: acoustic
spec:
  selector:
    app: acoustic
  type: NodePort
  ports:
    - port: 8067
      nodePort: 30030
      name: acoustic