apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim
          imagePullPolicy: Always
          ports:
            - containerPort: 9411
              protocol: TCP
          env:
          #- name: STORAGE_TYPE
          #  value: elasticsearch
          #- name: ES_HOSTS
          #  value: https://my-es-host:9243
          #- name: ES_USERNAME
          #  value: myUser
          #- name: ES_PASSWORD
          #  value: myPassword
          #- name: ES_HTTP_LOGGING
          #  value: HEADERS
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: zipkin
          