apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokcer-test-deploy
  labels:
    app: docker-test
spec:
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
      - name: docker-test
        image: ${DOCKER_REPO}/docker-test:${DOCKER_TAG}
        ports:
        - containerPort: 8078