server:
 port: 8077
---
spring:
 profiles:    active:    - default
 application:
    name: acoustic-search
 sleuth:
    sampler:
      probability: 1.0
 zipkin:
    enabled: true
    base-url: http://10.152.183.113:9411/
 datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: admin
  password: admin
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        exclude:
        - beans
        include:
        - '*'
eureka:
  instance:
    prefer-ip-address: false
    hostname: acoustic-0
  client:
    enabled: false
    fetchRegistry: false
    register-with-eureka: false
    service-url:
     defaultZone: http://localhost:8067/eureka
---
logging:  level:    '[com.acoustic.search]': debug
    '[org.springframework.web]': info
    '[org.springframework.boot,logging.level.web]': info
    '[com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver]': warn  file:    path: /app/cicd/logs/acoustic-search.log
debug: false
