server:
 port: 8091

spring:
  devtools:
    add-properties: true
  profiles:
    active:
    - default 
  application:
    name: acoustic-users
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://10.152.183.113:9411
  datasource:
   url: jdbc:postgresql://localhost:32143/acoustic?ApplicationName=niks_acoustic
   driver-class-name: org.postgresql.Driver
   username: root
   password: root
  jpa:
   properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true          

management:
  endpoints:
    web:
      exposure:
        exclude:
        - beans
        include:
        - '*'

eureka:
  instance:
    prefer-ip-address: false
    hostname: acoustic-0
  client:
    enabled: false
    fetchRegistry: false
    register-with-eureka: false
    service-url:
     defaultZone: http://localhost:8067/eureka

---
logging:
  level:
    '[io.netty.handler.codec.string]': info
    '[com.acoustic.users]': debug
    '[org.springframework.web]': info
    '[org.springframework.boot,logging.level.web]': info
    '[com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver]': warn
  file:
    path: /app/cicd/logs/users.log
debug: false
---
logging:
  level:
    root: INFO

test:
  flag: true
