name: Test CICD Tag
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    outputs: 
       output1: ${{ steps.TAG.outputs.TAG }}
    
    steps:
    - name: Clean previous repos
      run: rm -r -f tags
    - name: Checkout Tag CICD DEMO
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: tags
    - id: TAG
      run: |
          COMMIT_ID=`git rev-list --tags --date-order | head -1`
          TAG=`git show-ref --tags | grep $COMMIT_ID | awk -F / '{print  $NF}'`
          echo commitId:$COMMIT_ID and tag:$TAG
          echo "::set-output name=TAG::$TAG" 
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD        

    - name: List Dirs In OS
      run: |
           ls -l
           pwd
    - name: Building and Pushing TAG-Test-Service
      run: |
           export DOCKER_REPO=$DOCKER_REPO
           echo 'tag=========:'${{ steps.TAG.outputs.TAG }}
           mvn package dockerfile:push --file tags/docker-test/pom.xml
      env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          DOCKER_TAG: latest
  Deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: kubectl - Tag Test deployment.
      env:
         DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      run: |
          export DOCKER_REPO=$DOCKER_REPO
          export DOCKER_TAG=latest
          ls -l
          echo current working dir
          pwd
          echo 'docker repo is >>>>>' $DOCKER_REPO
          echo 'docker tag is  >>>>>' ${{needs.build.outputs.output1}}
          cat tags/cicd-demo-k8s/docker-test-tag-deploy.yml | sed -e 's/${DOCKER_REPO}/'$DOCKER_REPO'/g;s/${DOCKER_TAG}/'$DOCKER_TAG'/g'| microk8s kubectl apply -f -
          
